[package]
name = "visual_rank_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "visual_rank_engine"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.3", features = ["extension-module"] }
rand = "0.8" # 用于随机游走或初始化
